-- A guest workspace has one owner and a fixed expiry; the single showcase has neither.
CREATE TABLE workspace (
  id uuid PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('GUEST', 'SHOWCASE')),
  owner_id uuid,
  created_at timestamptz NOT NULL,
  expires_at timestamptz,
  CONSTRAINT workspace_guest_owned CHECK (
    (kind = 'GUEST') = (owner_id IS NOT NULL)
    AND (kind = 'GUEST') = (expires_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX workspace_single_showcase ON workspace (kind) WHERE kind = 'SHOWCASE';
CREATE INDEX workspace_kind_created ON workspace (kind, created_at);
CREATE INDEX workspace_expires ON workspace (expires_at) WHERE expires_at IS NOT NULL;

INSERT INTO workspace (id, kind, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'SHOWCASE', now());

-- Spring Session JDBC tables, copied from spring-session-jdbc 4.1.1 schema-postgresql.sql.
CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
